// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import taxobj "github.com/fairyhunter13/tax-calculator/internal/taxobj"

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// CreateTaxObject provides a mock function with given fields: _a0
func (_m *Usecase) CreateTaxObject(_a0 *taxobj.TaxObject) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*taxobj.TaxObject) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
